[package]
name = "test_crate"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cucumber = "0.19.1"
tokio = { version = "*", features = ["full"] }
